DATASET:
  name: "VOC"
  data_dir: "./data/pascal/VOCdevkit/VOC2012/"
  data_split: "trainaug"
  input_size: (328, 328)
  padding_constant: 8
  segm_downsampling_rate: 8

TASK:
  n_ways: 1
  n_shots: 1
  n_queries: 1
  fold_idx: 1

MODEL:
  arch_objectness: "resnet50_deeplab"
  arch_decoder: "c1_nodropout"
  fc_dim: 2048
  decoder_dim: 2048
  use_dropout: False

TRAIN:
  n_iters: 600000
  start_iter: 0
  n_batch: 4
  optim: "SGD"
  lr_encoder: 0.002
  lr_decoder: 0.002
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 4
  disp_iter: 200
  seed: 304
  save_freq: 100000
  eval_freq: 5000
  fix_encoder: False

VAL:
  n_runs: 3
  visualize: False
  checkpoint: "iter_10000.pth"

TEST:
  checkpoint: "epoch_25.pth"
  result: "./"

DIR: "ckpt/resnet50deeplabobject-c1-fc2048-voc-fold1-ways1-shots1"
