DATASET:
  name: "VOC"
  data_dir: "./data/pascal/VOCdevkit/VOC2012/"
  data_split: "trainaug"
  input_size: (256, 256)
  padding_constant: 8
  segm_downsampling_rate: 8

TASK:
  n_ways: 1
  n_shots: 1
  n_queries: 1
  fold_idx: 1

MODEL:
  arch_encoder: "resnet18dilated"
  memory_encoder_arch: "resnet18dilated_noBN"
  arch_attention: "attention_double"
  arch_decoder: "c1_channel3"
  mask_feat_downsample_rate: 1
  att_mat_downsample_rate: 1
  fc_dim: 512
  att_fc_dim: 512
  normalize_key: True
  p_scalar: 100.0
  att_voting: True

TRAIN:
  n_iters: 60000
  start_iter: 0
  n_batch: 8
  optim: "SGD"
  lr_encoder: 0.002
  lr_decoder: 0.002
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 4
  disp_iter: 20
  seed: 304
  save_freq: 10000
  permute_labels: False

VAL:
  n_runs: 3
  visualize: False
  checkpoint: "iter_10000.pth"

TEST:
  checkpoint: "epoch_25.pth"
  result: "./"

DIR: "ckpt/resnet18dilated-c1channel3-normKey-attVoting-voc-fold1-ways1-shots1"
