DATASET:
  name: "VOC"
  data_dir: "./data/pascal/VOCdevkit/VOC2012/"
  data_split: "trainaug"
  input_size: (328, 328)
  padding_constant: 8
  segm_downsampling_rate: 8
  exclude_labels: True

TASK:
  n_ways: 1
  n_shots: 1
  n_queries: 1
  fold_idx: 2

MODEL:
  arch_encoder: "resnet50_deeplab"
  arch_memory_encoder: "c1"
  arch_attention: "attention"
  arch_decoder: "aspp_few_shot"
  mask_feat_downsample_rate: 1
  att_mat_downsample_rate: 1
  objectness_feat_downsample_rate: 2
  fc_dim: 512
  encoder_dim: 1536
  decoder_dim: 513
  decoder_fc_dim: 256
  normalize_key: False
  global_pool_read: True
  use_dropout: True
  dropout_rate: 0.5
  mask_foreground: True
  average_memory_voting: False
  average_memory_voting_nonorm: False
  weights_objectness: 'ckpt/hrnetv2object-c1-fc720-voc-fold2-ways1-shots1/objectness_iter_best.pth'
  weights_objectness_decoder: 'ckpt/hrnetv2object-c1-fc720-voc-fold2-ways1-shots1/objectness_decoder_iter_best.pth'

TRAIN:
  n_iters: 600000
  start_iter: 0
  n_batch: 4
  optim: "SGD"
  lr_encoder: 0.0025
  lr_decoder: 0.0025
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 4
  disp_iter: 200
  seed: 304
  save_freq: 200000
  eval_freq: 10000
  permute_labels: False
  fix_encoder: True

VAL:
  n_runs: 3
  visualize: False
  checkpoint: "iter_10000.pth"

TEST:
  checkpoint: "epoch_25.pth"
  result: "./"

DIR: "ckpt/resnet50deeplab-excludeLabels-globalPool-hrnetObjectness-att-aspp-dropout5e1-fc256-voc-fold2-ways1-shots1"
